export const courses: { name: string, img:string, price: number; teacher:string, teachershort: string, teacherlong: string, locationshort: string, locationlong: string, duration: number, availability: boolean, id: number, quantity: number} []=[{
    name: "HTML+CSS",
    img: "assets/htmlcss.png",
    price: 250,
    teacher: "Mr. Johnson",
    teachershort: "Mr. Johnson, a seasoned software engineer, brings a wealth of industry experience to the programming course.",
    teacherlong: "With over 15 years of experience in software development, Mr. Johnson engages students with real-world examples, making complex concepts easy to understand. Students gain practical skills and valuable insights into the software development industry under his guidance.",
    locationshort: "Virtual Classroom",
    locationlong: "The virtual classroom allows students to access live lectures, interactive discussions, and collaborative coding exercises from anywhere, providing a flexible and immersive learning experience.",
    duration: 7,
    availability: true,
    id: 1,
    quantity: 0
},  {
    name: "Javascript",
    img: "assets/Javascript.png",
    price: 750,
    teacher: "Ms. Patel",
    teachershort: "Ms. Patel, an enthusiastic educator, focuses on creating a supportive and inclusive learning environment in her programming course.",
    teacherlong: "Ms. Patel fosters collaboration, ensuring that every student feels comfortable participating. Her teaching approach combines theory with hands-on projects, encouraging students to apply their knowledge and build confidence in their programming skills.",
    locationshort: "Tech Academy",
    locationlong: "The Tech Academy offers modern classrooms equipped with cutting-edge technology, providing an optimal learning environment for programming courses.",
    duration: 14,
    availability: true,
    id: 2,
    quantity: 0
},  {
    name: "Php",
    img: "assets/php.png",
    price: 2250,
    teacher: "Dr. Nguyen",
    teachershort: "Dr. Nguyen, a renowned researcher, brings cutting-edge knowledge and innovative teaching methods to the programming course.",
    teacherlong: "Dr. Nguyen incorporates his research findings into the curriculum, exposing students to emerging programming paradigms and industry advancements. His analytical approach encourages critical thinking and pushes students to explore new ideas, fostering a deep understanding of programming principles.",
    locationshort: "Community Center",
    locationlong: "The community center provides a friendly and inclusive atmosphere, where students can connect with peers, engage in discussions, and explore programming concepts together.",
    duration: 30,
    availability: true,
    id: 3,
    quantity: 0
},  {
    name: "Java",
    img: "assets/java.png",
    price: 2000,
    teacher: "Ms. Lee",
    teachershort: "Ms. Lee, a charismatic coding enthusiast, inspires students with her passion for programming and creative problem-solving.",
    teacherlong: "Ms. Lee's energetic teaching style and interactive activities keep students engaged and motivated. She challenges students to find unique solutions to coding problems, fostering a love for programming beyond the classroom.",
    locationshort: "Co-working Space",
    locationlong: "The co-working space provides a vibrant atmosphere, encouraging collaboration, idea-sharing, and networking opportunities among students in programming courses.",
    duration: 30,
    availability: true,
    id: 4,
    quantity: 0
},  {
    name: "C",
    img: "assets/C.png",
    price: 2500,
    teacher: "Mr. Rodriguez",
    teachershort: "Mr. Rodriguez, a patient and empathetic instructor, tailors his teaching approach to accommodate diverse learning styles.",
    teacherlong: "Mr. Rodriguez employs a variety of teaching methods, such as visual aids and one-on-one guidance, to support individual growth. Students receive personalized attention and build a solid foundation in programming.",
    locationshort: "University Campus",
    locationlong: "The university campus offers well-equipped classrooms, computer labs, and access to academic resources, fostering a scholarly environment for programming education.",
    duration: 35,
    availability: true,
    id: 5,
    quantity: 0
},  {
    name: "Python",
    img: "assets/python2.png",
    price: 3200,
    teacher: "Dr. Kim",
    teachershort: "Dr. Kim, an expert in algorithm design, equips students with advanced problem-solving techniques.",
    teacherlong: "Dr. Kim's deep understanding of algorithms helps students tackle complex programming challenges. Through his guidance, students gain skills to excel in competitive programming contests and real-world development scenarios.",
    locationshort: "Maker's Lab",
    locationlong: "The maker's lab is equipped with advanced hardware devices and tools, allowing students to experiment, prototype, and bring their programming ideas to life.",
    duration: 32,
    availability: true,
    id: 6,
    quantity: 0
}]