export const courses: { name: string, img: string, price: number; teacher: string, teachershort: string, teacherlong: string, locationshort: string, locationlong: string, duration: number, skillLevel: string, availability: boolean, id: number, quantity: number }[] = [{
    name: "HTML+CSS",
    img: "/assets/htmlcss.png",
    price: 250,
    teacher: "Bogdan Moisoiu",
    teachershort: "Bogdan, an expert in algorithm design and a seasoned software engineer, brings a wealth of industry experience to the programming course.",
    teacherlong: "With over 15 years of experience in software development, Mr. Moisoiu engages students with real-world examples, making complex concepts easy to understand. Students gain practical skills and valuable insights into the software development industry under his guidance.",
    locationshort: "Virtual Classroom",
    locationlong: "The virtual classroom allows students to access live lectures, interactive discussions, and collaborative coding exercises from anywhere, providing a flexible and immersive learning experience.",
    duration: 7,
    skillLevel: "Intro",
    availability: true,
    id: 1,
    quantity: 0
}, {
    name: "Javascript",
    img: "/assets/Javascript.png",
    price: 750,
    teacher: "Winston Ngwa",
    teachershort: "Winston, an enthusiastic educator, focuses on creating a supportive and inclusive learning environment in his programming course.",
    teacherlong: "Mr. Ngwa fosters collaboration, ensuring that every student feels comfortable participating. His teaching approach combines theory with hands-on projects, encouraging students to apply their knowledge and build confidence in their programming skills.",
    locationshort: "Tech Academy",
    locationlong: "The Tech Academy offers modern classrooms equipped with cutting-edge technology, providing an optimal learning environment for programming courses.",
    duration: 14,
    skillLevel: "Intro",
    availability: true,
    id: 2,
    quantity: 0
}, {
    name: "Php",
    img: "/assets/php.png",
    price: 2250,
    teacher: "Natasa Cvrlja",
    teachershort: "Natasa, a renowned researcher, brings cutting-edge knowledge and innovative teaching methods to the programming course.",
    teacherlong: "Dr. Cvrlja incorporates her research findings into the curriculum, exposing students to emerging programming paradigms and industry advancements. Her analytical approach encourages critical thinking and pushes students to explore new ideas, fostering a deep understanding of programming principles.",
    locationshort: "Community Center",
    locationlong: "The community center provides a friendly and inclusive atmosphere, where students can connect with peers, engage in discussions, and explore programming concepts together.",
    duration: 30,
    skillLevel: "Advanced",
    availability: true,
    id: 3,
    quantity: 0
}, {
    name: "Java",
    img: "/assets/java.png",
    price: 2000,
    teacher: "Narek Shahverdyan",
    teachershort: "Narek, a charismatic coding enthusiast, inspires students with his passion for programming and creative problem-solving.",
    teacherlong: "Mr. Shahverdyan energetic teaching style and interactive activities keep students engaged and motivated. He challenges students to find unique solutions to coding problems, fostering a love for programming beyond the classroom.",
    locationshort: "Co-working Space",
    locationlong: "The co-working space provides a vibrant atmosphere, encouraging collaboration, idea-sharing, and networking opportunities among students in programming courses.",
    duration: 30,
    skillLevel: "Basic",
    availability: true,
    id: 4,
    quantity: 0
}, {
    name: "C",
    img: "/assets/C.png",
    price: 2500,
    teacher: "Achmed Midajew",
    teachershort: "Achmed, a patient and empathetic instructor, tailors his teaching approach to accommodate diverse learning styles.",
    teacherlong: "Mr. Midajew employs a variety of teaching methods, such as visual aids and one-on-one guidance, to support individual growth. Students receive personalized attention and build a solid foundation in programming.",
    locationshort: "University Campus",
    locationlong: "The university campus offers well-equipped classrooms, computer labs, and access to academic resources, fostering a scholarly environment for programming education.",
    duration: 35,
    skillLevel: "Basic",
    availability: true,
    id: 5,
    quantity: 0
}, {
    name: "Python",
    img: "/assets/python2.png",
    price: 3200,
    teacher: "Bogdan Moisoiu",
    teachershort: "Bogdan, an expert in algorithm design and a seasoned software engineer, equips students with advanced problem-solving techniques.",
    teacherlong: "Dr. Moisoiu´s deep understanding of algorithms helps students tackle complex programming challenges. Through his guidance, students gain skills to excel in competitive programming contests and real-world development scenarios.",
    locationshort: "Maker's Lab",
    locationlong: "The maker's lab is equipped with advanced hardware devices and tools, allowing students to experiment, prototype, and bring their programming ideas to life.",
    duration: 32,
    skillLevel: "Advanced",
    availability: true,
    id: 6,
    quantity: 0
}]