export const courses: { name: string, img: string, description: string, price: number; teacher: string, teachershort: string, teacherlong: string, locationshort: string, locationlong: string, duration: number, skillLevel: string, availability: boolean, id: number, quantity: number }[] = [{
    name: "HTML+CSS",
    img: "/assets/htmlcss.png",
    description: "This course gets you the best for starters!",
    price: 250,
    teacher: "Bogdan Moisoiu",
    teachershort: "Bogdan, an expert in algorithm design and a seasoned software engineer, brings a wealth of industry experience to the programming course.",
    teacherlong: "The HTML and CSS Intro course is designed to provide students with a solid foundation in building and styling websites. Whether you're a beginner looking to enter the world of web development or an experienced programmer seeking to enhance your skills, this course will equip you with the knowledge and practical experience needed to create visually appealing and functional web pages.",
    locationshort: "Virtual Classroom",
    locationlong: "The virtual classroom allows students to access live lectures, interactive discussions, and collaborative coding exercises from anywhere, providing a flexible and immersive learning experience.",
    duration: 7,
    skillLevel: "Intro",
    availability: true,
    id: 1,
    quantity: 0
}, {
    name: "Javascript",
    img: "/assets/Javascript.png",
    description: "This course gets you the best hiring chance!",
    price: 750,
    teacher: "Winston Ngwa",
    teachershort: "Winston, an enthusiastic educator, focuses on creating a supportive and inclusive learning environment in his programming course.",
    teacherlong: "The JavaScript Intro course is a comprehensive introduction to one of the most widely used programming languages for web development. Throughout the course, you'll explore the core concepts of JavaScript, including variables, data types, functions, loops, and conditional statements. You'll learn how to manipulate the Document Object Model (DOM) to dynamically update web pages and interact with user input. ",
    locationshort: "Tech Academy",
    locationlong: "The Tech Academy offers modern classrooms equipped with cutting-edge technology, providing an optimal learning environment for programming courses.",
    duration: 14,
    skillLevel: "Intro",
    availability: true,
    id: 2,
    quantity: 0
}, {
    name: "Php",
    img: "/assets/php.png",
    description: "After finishing this course you are ready for backend!",
    price: 2250,
    teacher: "Natasa Cvrlja",
    teachershort: "Natasa, a renowned researcher, brings cutting-edge knowledge and innovative teaching methods to the programming course.",
    teacherlong: "The PHP Web Development Advanced course is a comprehensive program designed to equip students with the fundamental skills needed to create dynamic and robust web applications using PHP. Throughout the course, you'll explore the core concepts of PHP, including variables, data types, control structures, arrays, and functions. You'll learn how to interact with databases using MySQL and perform common tasks such as retrieving and manipulating data.",
    locationshort: "Community Center",
    locationlong: "The community center provides a friendly and inclusive atmosphere, where students can connect with peers, engage in discussions, and explore programming concepts together.",
    duration: 30,
    skillLevel: "Advanced",
    availability: true,
    id: 3,
    quantity: 0
}, {
    name: "Java",
    img: "/assets/java.png",
    description: "This course is for backend junkys!",
    price: 2000,
    teacher: "Narek Shahverdyan",
    teachershort: "Narek, a charismatic coding enthusiast, inspires students with his passion for programming and creative problem-solving.",
    teacherlong: "The Java Programming Basic course is a comprehensive program designed to introduce students to the world of Java programming. Throughout the course, you'll delve into the core concepts of Java, including variables, data types, control structures, object-oriented programming (OOP), classes, and methods. You'll learn how to write clean and efficient code, implement inheritance and polymorphism, handle exceptions, and work with Java libraries and APIs.",
    locationshort: "Co-working Space",
    locationlong: "The co-working space provides a vibrant atmosphere, encouraging collaboration, idea-sharing, and networking opportunities among students in programming courses.",
    duration: 30,
    skillLevel: "Basic",
    availability: true,
    id: 4,
    quantity: 0
}, {
    name: "C",
    img: "/assets/C.png",
    price: 2500,
    teacher: "Achmed Midajew",
    description: "This course will make you a backend monster!",
    teachershort: "Achmed, a patient and empathetic instructor, tailors his teaching approach to accommodate diverse learning styles.",
    teacherlong: "The C Programming Basic course is a comprehensive program designed to introduce students to the foundational concepts of the C programming language. Throughout the course, you'll explore the core principles of C programming, including variables, data types, control structures, functions, arrays, and pointers. You'll learn how to write efficient and structured code, work with input and output operations, and handle memory management effectively.",
    locationshort: "University Campus",
    locationlong: "The university campus offers well-equipped classrooms, computer labs, and access to academic resources, fostering a scholarly environment for programming education.",
    duration: 35,
    skillLevel: "Basic",
    availability: true,
    id: 5,
    quantity: 0
}, {
    name: "Python",
    img: "/assets/python2.png",
    description: "This course is going to make your wishes true!",
    price: 3200,
    teacher: "Bogdan Moisoiu",
    teachershort: "Bogdan, an expert in algorithm design and a seasoned software engineer, equips students with advanced problem-solving techniques.",
    teacherlong: "The Python Programming Advanced course is a comprehensive program designed to introduce students to the world of Python programming. Throughout the course, you'll explore the core concepts of Python, including variables, data types, control structures, functions, modules, and object-oriented programming (OOP). You'll learn how to write clean and readable code, manipulate strings and lists, handle exceptions, and work with files and databases.",
    locationshort: "Maker's Lab",
    locationlong: "The maker's lab is equipped with advanced hardware devices and tools, allowing students to experiment, prototype, and bring their programming ideas to life.",
    duration: 32,
    skillLevel: "Advanced",
    availability: true,
    id: 6,
    quantity: 0
}]