export const news = [{
    name: "Last course",
    picture: "./assets/news.webp",
    about: "Our last course finished 25 persons!",
    description: "The CodeFactory Frontend Web Developer course prepares you for your versatile use as a Junior Frontend Web Developer. It is the first module of the fullstack Web Developer course, which you can also take separately. If desired, a continuation of the training in the backend part is possible. In this course you will learn the most common programming languages and frameworks, from HTML, CSS, and JavaScript to the sophisticated Angular Framework. Furthermore you will learn important basics in testing and project management. As a frontend web developer you have comprehensive knowledge in the area of web development of user interfaces and their design and you are proficient in many of the relevant programming languages. This allows you to work in web development as well as in software development. As a specialist you can use your coding skills to solve a wide range of tasks in the area of design implementation and creative design and often work closely with project managers by taking care of software and test planning as well as programming activities.",
},{
    name: "New courses",
    picture: "./assets/news.webp",
    about: "We have many new beginning courses, check them and feel free to ask if you have questions.",
    description: "The CodeFactory Frontend Web Developer course prepares you for your versatile use as a Junior Frontend Web Developer. It is the first module of the fullstack Web Developer course, which you can also take separately. If desired, a continuation of the training in the backend part is possible. In this course you will learn the most common programming languages and frameworks, from HTML, CSS, and JavaScript to the sophisticated Angular Framework. Furthermore you will learn important basics in testing and project management. As a frontend web developer you have comprehensive knowledge in the area of web development of user interfaces and their design and you are proficient in many of the relevant programming languages. This allows you to work in web development as well as in software development. As a specialist you can use your coding skills to solve a wide range of tasks in the area of design implementation and creative design and often work closely with project managers by taking care of software and test planning as well as programming activities.",
},{
    name: "2022 overview",
    picture: "./assets/news.webp",
    about: "New record number of people finished our courses",
    description: "The CodeFactory Frontend Web Developer course prepares you for your versatile use as a Junior Frontend Web Developer. It is the first module of the fullstack Web Developer course, which you can also take separately. If desired, a continuation of the training in the backend part is possible. In this course you will learn the most common programming languages and frameworks, from HTML, CSS, and JavaScript to the sophisticated Angular Framework. Furthermore you will learn important basics in testing and project management. As a frontend web developer you have comprehensive knowledge in the area of web development of user interfaces and their design and you are proficient in many of the relevant programming languages. This allows you to work in web development as well as in software development. As a specialist you can use your coding skills to solve a wide range of tasks in the area of design implementation and creative design and often work closely with project managers by taking care of software and test planning as well as programming activities.",
},{
    name: "WAFF",
    picture: "./assets/news.webp",
    about: "Opportunity for get a course that is financed by waff",
    description: "The CodeFactory Frontend Web Developer course prepares you for your versatile use as a Junior Frontend Web Developer. It is the first module of the fullstack Web Developer course, which you can also take separately. If desired, a continuation of the training in the backend part is possible. In this course you will learn the most common programming languages and frameworks, from HTML, CSS, and JavaScript to the sophisticated Angular Framework. Furthermore you will learn important basics in testing and project management. As a frontend web developer you have comprehensive knowledge in the area of web development of user interfaces and their design and you are proficient in many of the relevant programming languages. This allows you to work in web development as well as in software development. As a specialist you can use your coding skills to solve a wide range of tasks in the area of design implementation and creative design and often work closely with project managers by taking care of software and test planning as well as programming activities.",
}
// ,{
//     name: "fourth",
//     picture: "./assets/news.webp",
//     about: "This is just a short description hehehehe",
//     description: "The CodeFactory Frontend Web Developer course prepares you for your versatile use as a Junior Frontend Web Developer. It is the first module of the fullstack Web Developer course, which you can also take separately. If desired, a continuation of the training in the backend part is possible. In this course you will learn the most common programming languages and frameworks, from HTML, CSS, and JavaScript to the sophisticated Angular Framework. Furthermore you will learn important basics in testing and project management. As a frontend web developer you have comprehensive knowledge in the area of web development of user interfaces and their design and you are proficient in many of the relevant programming languages. This allows you to work in web development as well as in software development. As a specialist you can use your coding skills to solve a wide range of tasks in the area of design implementation and creative design and often work closely with project managers by taking care of software and test planning as well as programming activities.",
// },{
//     name: "fourth",
//     picture: "./assets/news.webp",
//     about: "This is just a short description hehehehe",
//     description: "The CodeFactory Frontend Web Developer course prepares you for your versatile use as a Junior Frontend Web Developer. It is the first module of the fullstack Web Developer course, which you can also take separately. If desired, a continuation of the training in the backend part is possible. In this course you will learn the most common programming languages and frameworks, from HTML, CSS, and JavaScript to the sophisticated Angular Framework. Furthermore you will learn important basics in testing and project management. As a frontend web developer you have comprehensive knowledge in the area of web development of user interfaces and their design and you are proficient in many of the relevant programming languages. This allows you to work in web development as well as in software development. As a specialist you can use your coding skills to solve a wide range of tasks in the area of design implementation and creative design and often work closely with project managers by taking care of software and test planning as well as programming activities.",
// },{
//     name: "fourth",
//     picture: "./assets/news.webp",
//     about: "This is just a short description hehehehe",
//     description: "The CodeFactory Frontend Web Developer course prepares you for your versatile use as a Junior Frontend Web Developer. It is the first module of the fullstack Web Developer course, which you can also take separately. If desired, a continuation of the training in the backend part is possible. In this course you will learn the most common programming languages and frameworks, from HTML, CSS, and JavaScript to the sophisticated Angular Framework. Furthermore you will learn important basics in testing and project management. As a frontend web developer you have comprehensive knowledge in the area of web development of user interfaces and their design and you are proficient in many of the relevant programming languages. This allows you to work in web development as well as in software development. As a specialist you can use your coding skills to solve a wide range of tasks in the area of design implementation and creative design and often work closely with project managers by taking care of software and test planning as well as programming activities.",
// }
]